Repository openshift/pagerduty-short-circuiter, pull requests merged in 2023-07, with the labels that each got.

#135 Update OWNERS
  OWNERS
Labels: approved, lgtm

#136 OSD-15612: Updated Readme for the latest release
  README.md
Labels: approved, lgtm, jira/valid-reference

#139 Update README.md
  README.md
Labels: tide/merge-method-squash, approved, lgtm

#137 OSD-15768: Bug Fix for AcknowledgedIncidents Page
  pkg/ui/constants.go
  pkg/ui/events.go
  pkg/ui/input.go
  pkg/ui/seeders.go
  pkg/ui/tui.go
Labels: approved, lgtm, jira/valid-reference

#138 OSD-16101: Fixed Bug on handling process exit in TMUX
  go.mod
  go.sum
  pkg/ui/input.go
  pkg/ui/tab.go
  pkg/ui/terminal.go
Labels: approved, lgtm, jira/valid-reference
